import broken
import unittest

class TestException(unittest.TestCase):

	def testRaise(self):
		raise KeyError()


